language: node_js

node_js:
  - "6"

sudo: required

services:
  - docker

before_install:
  - docker pull isagroup/minizinc

before_script:
  - npm install grunt-cli -g

script:
  - docker run -t -v ./:/usr/src/app/governify-csp-tools isagroup/minizinc bash -c "cd /usr/src/app/governify-csp-tools && npm install && npm run localTests && npm run remoteTests"
  - npm run dockerTests

after_success:
  - REGEXP="release\s[0-9]+\.[0-9]+\.[0-9]+";
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_COMMIT_MESSAGE" =~ $REGEXP ]]; then
    grunt build;
    fi
